version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume111:/home/project/standardization/static/
    ports:
      - 8000:8000
    env_file:
      - ./standardization/.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data111:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=standardization
  nginx:
    build: ./nginx
    volumes:
      - static_volume111:/home/project/standardization/static/
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data111:
  static_volume111:
